version: '3.7'

services:

   geo-data-mongodb:
       image: mongo:4.2.7
       container_name: geo-data-mongodb
       hostname: geo-data-mongodb
       environment:
           MONGO_INITDB_DATABASE: geo-data-streaming
       ports:
           - 4250:27017
       networks:
          - geo-data-streaming-network
       healthcheck:
            test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
            interval: 10s
            start_period: 30s
       command: ["--replSet", "rs0", "--bind_ip_all"]
           
   geo-data-generator:
       build:
          context: .
          dockerfile: Dockerfile.geo-data-generator
       image: geo-data-generator:latest
       container_name: geo-data-generator
       environment:
          MONGO_DB_URI: mongodb://geo-data-mongodb/geo-data-streaming
       depends_on:
          - geo-data-mongodb
       networks:
          - geo-data-streaming-network
       
networks:
   geo-data-streaming-network:
      name: geo-data-streaming-network
      driver: bridge