# First layer, vaven image to build the project
FROM maven:3.6.3-openjdk-8-slim as BUILDER
# Copy parent pom
COPY pom.xml .
# Set work directory
WORKDIR geo-data-kafka-streams
# Copy the project
COPY ./geo-data-kafka-streams/pom.xml .
# Download dependencies
RUN mvn dependency:go-offline
# Copy src
COPY ./geo-data-kafka-streams/src ./src
# Build the project
RUN mvn clean package --projects :geo-data-kafka-streams

# Second layer
FROM openjdk:8-jre
# Set work directory
WORKDIR geo-data-kafka-streams
# Copy the jar from the BUILDER layer
COPY --from=BUILDER ./geo-data-kafka-streams/target/*.jar ./geo-data-kafka-streams.jar
# Create start script
RUN echo "echo Waiting for 15 seconds..." >> start.sh && \
	echo "sleep 15" >> start.sh && \
	echo "echo Starting geo-data-kafka-streams..." >> start.sh && \
	echo "java -jar ./geo-data-kafka-streams.jar" >> start.sh
# Give execution permission to start script
RUN ["chmod", "+x", "./start.sh"]
# Set the entrypoint for the app
ENTRYPOINT ["/bin/sh", "./start.sh"]